Repository wecode-bootcamp-korea/28-2nd-StayMemory-frontend, pull requests merged in 2022-01, with the labels that each got.

#5 [28기 이가윤] nav 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Location/Location.js
  src/components/Nav/Nav.js
  src/components/Nav/PopUp.js
  src/components/SelectDate/SelectDate.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlider.js
  src/pages/Main/SubSlider/SubSlider.js
Labels: Status: 수정 요청

#7 [28기 이가윤] 상세페이지 구현완료
  .env
  =#.##
  package-lock.json
  package.json
  public/data/detail.json
  public/images/room.jpg
  src/components/KakaoLogin/KakaoLogin.js
  src/components/SelectDate/Calendar.js
  src/components/SelectDate/SelectDate.js
  src/components/SelectDate/SelectDateFindStay.js
  src/pages/Detail/Detail.js
Labels: Status: Conflict 해결 요청

#4 [28기 이가윤] 소셜로그인 백엔드 통신 완료 / 수정 사항 반영 완료
  .env
  .gitignore
  =#.##
  public/index.html
  src/Router.js
  src/components/KakaoLogin/KakaoLogin.js
  src/components/SelectDate/Calendar4.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#8 [28기 옥채현] My page 레이아웃 구현
  .env
  public/data/myPageData.json
  public/data/welcomeData.json
  src/components/PageBtn.js
  src/pages/Login/Login.js
  src/pages/MyPage/MyPage.js
Labels: Status: 리뷰 요청

#14 [28기 이가윤] Feature/nav key 값 수정
  package-lock.json
  src/components/Modal/GlobalState.js
  src/components/Modal/SelectDate/SelectDate.js
  src/components/Modal/SelectDate/SelectDateFindStay.js
  src/pages/Detail/Detail.js
Labels: Status: 리뷰 요청

#13 [28기 옥채현] Add: 카카오 소셜로그인 버튼 css
  public/images/kakaoBtn.png
  src/Router.js
  src/components/KakaoLogin/KakaoLogin.js
  src/components/OAuth/Oauth.js
  src/pages/Login/Login.js
Labels: Status: Conflict 해결 요청, Status: 수정 요청

#12 [28기 이가윤] Feature/mypage-reservation 예약정보/다녀온 스테이 구현 완료, 백엔드 통신 예정
  src/Router.js
  src/pages/MyPage/MyPage.js
Labels: Status: Rebase 요청

#15 [28기 옥채현] Modify:Login 페이지 css 수정
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청
